### ISSUE TITLE
Project ID

### ISSUE THREAD

**Issue by ghost** [bvasiles/diversity#2]
Dear Bogdan,

Would it be possible for you to create a column of just the Project ID's? I am wondering for a project that I am working on!

Thanks!
Eric

**Comment by bvasiles** [comment]
Hi Eric,

The second column `project_id` is already the project ID. These match project IDs in GHTorrent http://ghtorrent.org
Is this what you mean?

Cheers!

**Comment by ghost** [comment]
Hi Bogdan,

That is helpful, I am now trying to go through the database and get the project url's based on the ids, but it's not easy:/ I guess I'll have to download those two columns of data?

Cheers!

**Comment by bvasiles** [comment]
I can tell you which id your project has if you tell me its name.

**Comment by ghost** [comment]
Oh ok! I actually have a set of 9,000 ids, and I was trying to get their corresponding urls, but I'm not really sure how to do that in an automated way?

**Comment by bvasiles** [comment]
Added a column with the login of the project owner in 6dca9b4f. You can assemble the GH stub now with the owner_login/name columns.

**Comment by ghost** [comment]
Thank you so much!:)
